### ISSUE TITLE
"Producer Interactions" Enhancements

### ISSUE THREAD

**Issue by RichardBruskiewich** [broadinstitute/sharpener-gui#1]
This issue is a global issue to aggregate ideas for enhancement of the Producer Interactions (gene list creation) activity in the STAR-GUI.

- [ ] Since _Producer (Gene List Creation) Interactions_ are infrequent operations relative to the gene sharpener workflow interactions, perhaps segregating these interactions in their own dedicated _hide/show_ view would minimize UI clutter. This _hide/show_ view could be in a popup window or just a separate view on a Single Page Application (SPA) mode.  In the main application page, perhaps a clickable button "New Gene List" could trigger the exposure of the view; the view can be hidden again by the completion of a gene set creation exercise (*Create* button?) or by a *Cancel* button.

- [x] Within a dedicated Producer Interactions view, there could be (at the moment) four distinct ways to create a new gene list: raw gene identifier (multi-line text box + *Load* button); gene symbol (type ahead suggestions from HGNC gene symbols?+ *Submit* button); disease (name type ahead suggestions from MONDO disease ontology with *Submit* button) with MONDO ID (directly specified); and MGSigDb (display type ahead or a scrollable list of available MGSigDB gene lists, by name? Maybe type ahead search of the names? *Submit* button)

- [ ] A default human readable name should be given for the gene set but users can also specify their own name (in a single line text box) maybe controlled by an explicit "Edit" button.

**Comment by kennethbruskiewicz** [comment]
Stale, stakeholders prefer Producers to be on the same level of organization as other ways of populating the graph (debate is around whether it's closer to an transformer or something else)

Major producer improvements will be happening in https://github.com/broadinstitute/sharpener-gui/issues/66
