### ISSUE TITLE
numerical significant figures

### ISSUE THREAD

**Issue by remontoire-pac** [broadinstitute/sharpener-gui#13]
We should truncate display of numerical values to 3-4 significant figures (F7).

 F7
![image](https://user-images.githubusercontent.com/2120526/62887581-88dd3880-bd0b-11e9-9f04-9b6bfe39a57a.png)

**Comment by kennethbruskiewicz** [comment]
https://github.com/broadinstitute/sharpener-gui/commit/6f28f527a851ddd14eacc85c76e174c0b05bd209#diff-db00cd9e62431bb5e58b0ca5c1e40500R129
