### ISSUE TITLE
"Transformer Interactions" Enhancements

### ISSUE THREAD

**Issue by RichardBruskiewich** [broadinstitute/sharpener-gui#3]
This issue is a global issue to aggregate ideas for enhancement of the "Transformer Interactions" activity in the STAR-GUI.  Good core functionality.  Possible enhancements:

- [x] Some of the transformers will likely take a bit of time to execute. Some kind of "Busy" signal or "Progress bar" (insofar feasible) would be useful for the user to see the status of the computation

- [x] The hard coded screen positions of just two Transformers (so far) will, of course, not be scalable. Perhaps a scrollable window view for the list of available transformers will help here.  The parameters for each Transformer could be hide/show using the same clickable title bar as in the gene list.  

- [ ] Perhaps we need a visual indication to the user in the titlebar for the "hide/show" functionality of the titlebar here?

- [x] How might we render the "audit trail" of gene list transformations, somewhere here? Will's directed graph representation looks interesting in this regard.

**Comment by kennethbruskiewicz** [comment]
stale
