### ISSUE TITLE
Managing Columns in Gene Table: Show/Hide

### ISSUE THREAD

**Issue by kbruskiewicz** [broadinstitute/sharpener-gui#33]
- [x] Write a custom MultiValueRemove component to change icon to communicate more effectively
  - see [this](https://github.com/JedWatson/react-select/blob/b7868d23ccd0b9e623b277f971e89020d426fbdb/docs/examples/CustomMultiValueRemove.js)
- [ ] Synchronize defaults of toggled/hidden columns in Table and the default values of Select from the same computed state initialized on mount?

**Comment by kennethbruskiewicz** [comment]
We need to have a means to hide again from the cell rather than have it all in the select menu.
