### ISSUE TITLE
Validate Form Input

### ISSUE THREAD

**Issue by kbruskiewicz** [broadinstitute/sharpener-gui#34]
- [ ] Check that not blank
- [ ] Check that value is of right type
- [ ] Check that value is in appropriate format
- [ ] Check that value is in domain (Lookup issue)
- [ ] Show validation results upon completion
- [ ] Throw error to GUI for display on incomplete validation step
https://react-bootstrap.github.io/components/forms/#forms-validation-native

**Comment by kennethbruskiewicz** [comment]
Merging to #39
