### ISSUE TITLE
"Gene Aggregation" Enhancements

### ISSUE THREAD

**Issue by RichardBruskiewich** [broadinstitute/sharpener-gui#4]
This issue is a global issue to aggregate ideas for enhancement of the "Gene List Aggregation" activity in the STAR-GUI.

- [x] We would definitely want to (soon?) add interactive Venn diagrams and other GUI representations of sets.
- [x] Selections of "active" gene lists is currently visible under the Transformer "Expander" view, alongside set *Union* and *Intersection* buttons. There is perhaps a good argument in support of segregating the set aggregation operations of the UI in its own dedicated view or location on the layout, or at least, sandwiched in between the "Gene List Viewing" and "Transformer Iterations" part of the UI.  That said, the automatic substitution of a union or intersection set as the "currently selected set" is a convenient feature!

- [ ] It may be helpful to have some way of directly viewing the list of genes in the selected sets. Colour coding each entry in a manner relating to its set status in the Venn diagram (i.e. is it unique to a given gene list or shared between two gene lists?).

**Comment by kennethbruskiewicz** [comment]
Stale, although that last item may be revisited in a separate issue.
